export enum PermissionGroup {
  AUTHENTICATION = 'AUTHENTICATION',
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  ROLE_MANAGEMENT = 'ROLE_MANAGEMENT',
  PERMISSION_MANAGEMENT = 'PERMISSION_MANAGEMENT',
  PRODUCT = 'PRODUCT',
  CATEGORY = 'CATEGORY',
  BRAND = 'BRAND',
  ATTRIBUTE = 'ATTRIBUTE',
  MEDIA = 'MEDIA',
  ORDER = 'ORDER',
  DASHBOARD = 'DASHBOARD',
  SETTINGS = 'SETTINGS',
}

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  CATALOG_MANAGER = 'CATALOG_MANAGER',
  SUPPORT_AGENT = 'SUPPORT_AGENT',
  VIEWER = 'VIEWER',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  LOCKED = 'LOCKED',
}

export enum MediaType {
  IMAGE,
  VIDEO,
  DOCUMENT,
  OTHER,
}

export enum MediaStatus {
  PENDING,
  PROCESSING,
  READY,
  ERROR,
}

export enum BrandStatus {
  ACTIVE,
  INACTIVE,
}